### ISSUE TITLE
mvnd -version does not work

### ISSUE THREAD

**Issue by ppalaga** [gnodet/mvnd#2]
I'd expect `mvnd -version` to return the same output as `mvn -version`, but it just hangs.

**Comment by Dunemaster** [comment]
Actually, running mvnd --version still does not work

E:\dev>"E:\Program Files\mvnd\mvnd-windows-amd64" --version
Jun 29, 2020 3:13:03 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
[1mMaven Daemon 0.0.0 (native)[m
Exception in thread "main" java.lang.IllegalStateException: Could not detect maven.multiModuleProjectDirectory by climbing up from [E:\dev] seeking a .mvn directory. You may want to create a .mvn directory in the root directory of your source tree.
        at org.jboss.fuse.mvnd.client.Environment.lambda$findMultiModuleProjectDirectory$4(Environment.java:127)
        at org.jboss.fuse.mvnd.client.Environment$EnvValue.get(Environment.java:246)
        at org.jboss.fuse.mvnd.client.Environment$EnvValue.asPath(Environment.java:258)
        at org.jboss.fuse.mvnd.client.Environment.findMultiModuleProjectDirectory(Environment.java:131)
        at org.jboss.fuse.mvnd.client.ClientLayout.getEnvInstance(ClientLayout.java:45)
        at org.jboss.fuse.mvnd.client.DefaultClient.lambda$main$0(DefaultClient.java:69)
        at org.jboss.fuse.mvnd.client.DefaultClient.execute(DefaultClient.java:170)
        at org.jboss.fuse.mvnd.client.DefaultClient.main(DefaultClient.java:69)

while 

mvn --version produces

E:\dev>mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: E:\maven-3.6.2\bin\..
Java version: 11.0.7, vendor: BellSoft, runtime: C:\Program Files\BellSoft\LibericaJDK-11
Default locale: ru_RU, platform encoding: Cp1251
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
